### get all user 


# // [@author:[JTousMay]
query {
  getUsers {
    id
    email
    firstName
    lastName
    city
    country
    phoneNumber
    latitude
    longitude
  }
}


### Get users by id

query {
  getUser (id: 1) {  # Replace '1' with the actual ID returned from the createUser  mutation
    id
    email
    firstName
    lastName
    city
    country
    phoneNumber
    latitude
    longitude
  }
}


### create new one 

mutation {
  createUser  (input: {
    email: "lnxs@example.com",
    password: "securepassword",
    firstName: "lnxs",
    lastName: "lnxs",
    city: "Med",
    country: "Col",
    phoneNumber: "3104776764",
    latitude: 40.7128,
    longitude: -74.0060
  }) {
    id
    email
    firstName
    lastName
    city
    country
    phoneNumber
    latitude
    longitude
  }
}

## Update an Existing User


## Create Multiple Users


mutation {
  createMultipleUsers(createMultipleUsersData: {
    users: [
      {
        email: "user1@example.com",
        password: "password1",
        firstName: "User ",
        lastName: "One",
        city: "New York",
        country: "USA",
        phoneNumber: "1234567890",
        latitude: 40.7128,
        longitude: -74.0060
      },
      {
        email: "user2@example.com",
        password: "password2",
        firstName: "User ",
        lastName: "Two",
        city: "Los Angeles",
        country: "USA",
        phoneNumber: "0987654321",
        latitude: 34.0522,
        longitude: -118.2437
      },
      {
        email: "user3@example.com",
        password: "password3",
        firstName: "User ",
        lastName: "Three",
        city: "London",
        country: "UK",
        phoneNumber: "1122334455",
        latitude: 51.5074,
        longitude: -0.1278
      }
    ]
  }) {
    id
    email
    firstName
    lastName
    city
    country
    phoneNumber
    latitude
    longitude
  }
}
### Delete users

mutation {
  deleteUser (id: 1) {  // Replace with the actual user ID you want to delete
    id
    email
    latitude
    longitude
  }
}
